"""add_intelligence_tables

Revision ID: aaf2d53decf5
Revises: de5f80ddef91
Create Date: 2026-07-30 11:21:15.066643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aaf2d53decf5'
down_revision: Union[str, None] = 'de5f80ddef91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_conflicts',
    sa.Column('objective_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_a', sa.String(length=100), nullable=False),
    sa.Column('agent_b', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('disagreement', sa.Text(), nullable=False),
    sa.Column('evidence_a', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_b', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_conflicts_objective_id'), 'agent_conflicts', ['objective_id'], unique=False)
    op.create_index(op.f('ix_agent_conflicts_status'), 'agent_conflicts', ['status'], unique=False)
    op.create_table('agent_messages',
    sa.Column('objective_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('from_agent', sa.String(length=100), nullable=False),
    sa.Column('to_agent', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('parent_message_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.ForeignKeyConstraint(['parent_message_id'], ['agent_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_objective_id'), 'agent_messages', ['objective_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_parent_message_id'), 'agent_messages', ['parent_message_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_status'), 'agent_messages', ['status'], unique=False)
    op.create_table('approval_gates',
    sa.Column('objective_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('gate_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('proposed_by', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_paused', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_gates_objective_id'), 'approval_gates', ['objective_id'], unique=False)
    op.create_index(op.f('ix_approval_gates_status'), 'approval_gates', ['status'], unique=False)
    op.create_table('connector_configs',
    sa.Column('objective_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_configs_objective_id'), 'connector_configs', ['objective_id'], unique=False)
    op.create_index(op.f('ix_connector_configs_provider'), 'connector_configs', ['provider'], unique=False)
    op.create_index('ix_connector_configs_provider_status', 'connector_configs', ['provider', 'status'], unique=False)
    op.create_table('execution_checkpoints',
    sa.Column('objective_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('checkpoint_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_step', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('resume_count', sa.Integer(), nullable=False),
    sa.Column('last_resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_checkpoints_objective_id'), 'execution_checkpoints', ['objective_id'], unique=True)
    op.create_index(op.f('ix_execution_checkpoints_status'), 'execution_checkpoints', ['status'], unique=False)
    op.create_table('self_healing_actions',
    sa.Column('objective_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trigger_event', sa.String(length=500), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_self_healing_actions_objective_id'), 'self_healing_actions', ['objective_id'], unique=False)
    op.create_table('watchdog_alerts',
    sa.Column('objective_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchdog_alerts_alert_type'), 'watchdog_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_watchdog_alerts_objective_id'), 'watchdog_alerts', ['objective_id'], unique=False)
    op.create_table('connector_actions',
    sa.Column('connector_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('objective_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connector_configs.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connector_actions_connector', 'connector_actions', ['connector_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_connector_actions_connector_id'), 'connector_actions', ['connector_id'], unique=False)
    op.create_index(op.f('ix_connector_actions_objective_id'), 'connector_actions', ['objective_id'], unique=False)
    op.create_table('connector_webhooks',
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('connector_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('objective_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.Column('last_response', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connector_configs.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_webhooks_connector_id'), 'connector_webhooks', ['connector_id'], unique=False)
    op.create_index('ix_connector_webhooks_events', 'connector_webhooks', ['events'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_connector_webhooks_objective_id'), 'connector_webhooks', ['objective_id'], unique=False)
    op.create_table('connector_audit_logs',
    sa.Column('connector_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['connector_actions.id'], ),
    sa.ForeignKeyConstraint(['connector_id'], ['connector_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connector_audit_connector', 'connector_audit_logs', ['connector_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_connector_audit_logs_connector_id'), 'connector_audit_logs', ['connector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connector_audit_logs_connector_id'), table_name='connector_audit_logs')
    op.drop_index('ix_connector_audit_connector', table_name='connector_audit_logs')
    op.drop_table('connector_audit_logs')
    op.drop_index(op.f('ix_connector_webhooks_objective_id'), table_name='connector_webhooks')
    op.drop_index('ix_connector_webhooks_events', table_name='connector_webhooks', postgresql_using='gin')
    op.drop_index(op.f('ix_connector_webhooks_connector_id'), table_name='connector_webhooks')
    op.drop_table('connector_webhooks')
    op.drop_index(op.f('ix_connector_actions_objective_id'), table_name='connector_actions')
    op.drop_index(op.f('ix_connector_actions_connector_id'), table_name='connector_actions')
    op.drop_index('ix_connector_actions_connector', table_name='connector_actions')
    op.drop_table('connector_actions')
    op.drop_index(op.f('ix_watchdog_alerts_objective_id'), table_name='watchdog_alerts')
    op.drop_index(op.f('ix_watchdog_alerts_alert_type'), table_name='watchdog_alerts')
    op.drop_table('watchdog_alerts')
    op.drop_index(op.f('ix_self_healing_actions_objective_id'), table_name='self_healing_actions')
    op.drop_table('self_healing_actions')
    op.drop_index(op.f('ix_execution_checkpoints_status'), table_name='execution_checkpoints')
    op.drop_index(op.f('ix_execution_checkpoints_objective_id'), table_name='execution_checkpoints')
    op.drop_table('execution_checkpoints')
    op.drop_index('ix_connector_configs_provider_status', table_name='connector_configs')
    op.drop_index(op.f('ix_connector_configs_provider'), table_name='connector_configs')
    op.drop_index(op.f('ix_connector_configs_objective_id'), table_name='connector_configs')
    op.drop_table('connector_configs')
    op.drop_index(op.f('ix_approval_gates_status'), table_name='approval_gates')
    op.drop_index(op.f('ix_approval_gates_objective_id'), table_name='approval_gates')
    op.drop_table('approval_gates')
    op.drop_index(op.f('ix_agent_messages_status'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_parent_message_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_objective_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_agent_conflicts_status'), table_name='agent_conflicts')
    op.drop_index(op.f('ix_agent_conflicts_objective_id'), table_name='agent_conflicts')
    op.drop_table('agent_conflicts')
    # ### end Alembic commands ###
