"""add execution artifacts and telemetry tables

Revision ID: de5f80ddef91
Revises: 20260730_features_extensions
Create Date: 2026-07-29 22:46:43.989203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de5f80ddef91'
down_revision: Union[str, None] = '20260730_features_extensions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_telemetry',
    sa.Column('objective_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runtime_ms', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('input_cost', sa.Float(), nullable=True),
    sa.Column('output_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('parent_agents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('child_agents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upstream', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('downstream', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('decision_summary', sa.Text(), nullable=True),
    sa.Column('artifacts_produced', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('output_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_telemetry_objective', 'agent_telemetry', ['objective_id', 'agent_id'], unique=False)
    op.create_index(op.f('ix_agent_telemetry_objective_id'), 'agent_telemetry', ['objective_id'], unique=False)
    op.create_index('ix_agent_telemetry_stage', 'agent_telemetry', ['objective_id', 'stage'], unique=False)
    op.create_table('execution_events',
    sa.Column('objective_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('event_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_events_objective', 'execution_events', ['objective_id', 'event_order'], unique=False)
    op.create_index(op.f('ix_execution_events_objective_id'), 'execution_events', ['objective_id'], unique=False)
    op.create_table('execution_snapshots',
    sa.Column('objective_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_snapshots_objective', 'execution_snapshots', ['objective_id'], unique=True)
    op.create_index(op.f('ix_execution_snapshots_objective_id'), 'execution_snapshots', ['objective_id'], unique=True)
    op.create_foreign_key(None, 'jobs', 'objectives', ['objective_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'objective_compilations', ['objective_id'])
    op.create_foreign_key(None, 'objectives', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'objectives', type_='foreignkey')
    op.drop_constraint(None, 'objective_compilations', type_='unique')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_execution_snapshots_objective_id'), table_name='execution_snapshots')
    op.drop_index('ix_execution_snapshots_objective', table_name='execution_snapshots')
    op.drop_table('execution_snapshots')
    op.drop_index(op.f('ix_execution_events_objective_id'), table_name='execution_events')
    op.drop_index('ix_execution_events_objective', table_name='execution_events')
    op.drop_table('execution_events')
    op.drop_index('ix_agent_telemetry_stage', table_name='agent_telemetry')
    op.drop_index(op.f('ix_agent_telemetry_objective_id'), table_name='agent_telemetry')
    op.drop_index('ix_agent_telemetry_objective', table_name='agent_telemetry')
    op.drop_table('agent_telemetry')
    # ### end Alembic commands ###
